services:
  postgres:
    image: postgres:15-alpine
    container_name: budget-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5400"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "7070:7070"
    depends_on:
      - postgres
    networks:
      - budget-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budget-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - budget-network

volumes:
  postgres_data:

networks:
  budget-network:
    driver: bridge