spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/budgetdb
    username: budgetuser
    password: budgetpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true 

logging:
  level:
    com.budgetapp: TRACE
    org.springframework.security: INFO