spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/budgetdb
    username: budgetuser
    password: budgetpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    show-sql: true

logging:
  level:
    com.budgetapp: TRACE